[Wealthy]
; Green on dark grey background
text = B2738C
subtext = c0c0c3
nav-active-text = 060610
main = 060610
sidebar = 060610
player = 060610
card = 060610
shadow = 060610
main-secondary = 060610
button = 1F5B98
button-secondary = B2738C
button-active = 1F5B98
button-disabled    = 353535
nav-active = 4F6DA3
play-button = 1F5B98
tab-active = 060610
notification = B2738C
notification-error = 242424
playback-bar = 1F5B98
misc = B2738C

[Cherry]
; Pink on dark blue background
text = B2738C
subtext = c0c0c3
nav-active-text = 060610
main = 060610
sidebar = 060610
player = 060610
card = 060610
shadow = 060610
main-secondary = 060610
button = 1F5B98
button-secondary = B2738C
button-active = 1F5B98
button-disabled    = 192531
nav-active = 4F6DA3
play-button = 1F5B98
tab-active = 060610
notification = B2738C
notification-error = 192531
playback-bar = 1F5B98
misc = B2738C

[Coral]
; Salmon on dark blue background
text = B2738C
subtext = c0c0c3
nav-active-text = 060610
main = 060610
sidebar = 060610
player = 060610
card = 060610
shadow = 060610
main-secondary = 060610
button = 1F5B98
button-secondary = B2738C
button-active = 1F5B98
button-disabled    = 192531
nav-active = 4F6DA3
play-button = 1F5B98
tab-active = 060610
notification = B2738C
notification-error = 192531
playback-bar = 1F5B98
misc = B2738C

[Deep]
; White on dark blue background
text = B2738C
subtext = c0c0c3
nav-active-text = 060610
main = 060610
sidebar = 060610
player = 060610
card = 060610
shadow = 060610
main-secondary = 060610
button = 1F5B98
button-secondary = B2738C
button-active = 1F5B98
button-disabled    = 21282f
nav-active = 4F6DA3
play-button = 1F5B98
tab-active = 060610
notification = B2738C
notification-error = 051024
playback-bar = 1F5B98
misc = B2738C

[Greener]
; White on dark and green background
text = B2738C
subtext = c0c0c3
nav-active-text = 060610
main = 060610
sidebar = 060610
player = 060610
card = 060610
shadow = 060610
main-secondary = 060610
button = 1F5B98
button-secondary = B2738C
button-active = 1F5B98
button-disabled    = 21282f
nav-active = 4F6DA3
play-button = 1F5B98
tab-active = 060610
notification = B2738C
notification-error = 051024
playback-bar = 1F5B98
misc = B2738C

[Deeper]
; Light blue on dark background
text = B2738C
subtext = c0c0c3
nav-active-text = 060610
main = 060610
sidebar = 060610
player = 060610
card = 060610
shadow = 060610
main-secondary = 060610
button = 1F5B98
button-secondary = B2738C
button-active = 1F5B98
button-disabled    = 0C1C19
nav-active = 4F6DA3
play-button = 1F5B98
tab-active = 060610
notification = B2738C
notification-error = 051024
playback-bar = 1F5B98
misc = B2738C

[Psycho]
; Red on dark grey background
text = B2738C
subtext = c0c0c3
nav-active-text = 060610
main = 060610
sidebar = 060610
player = 060610
card = 060610
shadow = 060610
main-secondary = 060610
button = 1F5B98
button-secondary = B2738C
button-active = 1F5B98
button-disabled    = 404040
nav-active = 4F6DA3
play-button = 1F5B98
tab-active = 060610
notification = B2738C
notification-error = 5e0000
playback-bar = 1F5B98
misc = B2738C

[UltraBlack]
; White on black background
text = B2738C
subtext = c0c0c3
nav-active-text = 060610
main = 060610
sidebar = 060610
player = 060610
card = 060610
shadow = 060610
main-secondary = 060610
button = 1F5B98
button-secondary = B2738C
button-active = 1F5B98
button-disabled    = 2f2f2f
nav-active = 4F6DA3
play-button = 1F5B98
tab-active = 060610
notification = B2738C
notification-error = 292929
playback-bar = 1F5B98
misc = B2738C

[Nord]
; Light grey on blue background
text = B2738C
subtext = c0c0c3
nav-active-text = 060610
main = 060610
sidebar = 060610
player = 060610
card = 060610
shadow = 060610
main-secondary = 060610
button = 1F5B98
button-secondary = B2738C
button-active = 1F5B98
button-disabled    = 434C5E
nav-active = 4F6DA3
play-button = 1F5B98
tab-active = 060610
notification = B2738C
notification-error = 3b4252
playback-bar = 1F5B98
misc = B2738C

[Futura]
; Cyan on dark background
text = B2738C
subtext = c0c0c3
nav-active-text = 060610
main = 060610
sidebar = 060610
player = 060610
card = 060610
shadow = 060610
main-secondary = 060610
button = 1F5B98
button-secondary = B2738C
button-active = 1F5B98
button-disabled    = 3f3c45
nav-active = 4F6DA3
play-button = 1F5B98
tab-active = 060610
notification = B2738C
notification-error = 51485b
playback-bar = 1F5B98
misc = B2738C

[Elementary]
; Purple and pink on dark background
text = B2738C
subtext = c0c0c3
nav-active-text = 060610
main = 060610
sidebar = 060610
player = 060610
card = 060610
shadow = 060610
main-secondary = 060610
button = 1F5B98
button-secondary = B2738C
button-active = 1F5B98
button-disabled    = 2E303E
nav-active = 4F6DA3
play-button = 1F5B98
tab-active = 060610
notification = B2738C
notification-error = 2E2837
playback-bar = 1F5B98
misc = B2738C

[BladeRunner]
; Yellow, pink and blue on dark background
text = B2738C
subtext = c0c0c3
nav-active-text = 060610
main = 060610
sidebar = 060610
player = 060610
card = 060610
shadow = 060610
main-secondary = 060610
button = 1F5B98
button-secondary = B2738C
button-active = 1F5B98
button-disabled    = 242a2e
nav-active = 4F6DA3
play-button = 1F5B98
tab-active = 060610
notification = B2738C
notification-error = 131417
playback-bar = 1F5B98
misc = B2738C

[Dracula]
; https://draculatheme.com/contribute
text = B2738C
subtext = c0c0c3
nav-active-text = 060610
main = 060610
sidebar = 060610
player = 060610
card = 060610
shadow = 060610
main-secondary = 060610
button = 1F5B98
button-secondary = B2738C
button-active = 1F5B98
button-disabled    = 3f3c45
nav-active = 4F6DA3
play-button = 1F5B98
tab-active = 060610
notification = B2738C
notification-error = 1c1e26
playback-bar = 1F5B98
misc = B2738C

[VantaBlack]
; Gray on black background 
text = B2738C
subtext = c0c0c3
nav-active-text = 060610
main = 060610
sidebar = 060610
player = 060610
card = 060610
shadow = 060610
main-secondary = 060610
button = 1F5B98
button-secondary = B2738C
button-active = 1F5B98
button-disabled    = 000000
nav-active = 4F6DA3
play-button = 1F5B98
tab-active = 060610
notification = B2738C
notification-error = 000000
playback-bar = 1F5B98
misc = B2738C

[RosePine]
; https://rosepinetheme.com/palette
text = B2738C
subtext = c0c0c3
nav-active-text = 060610
main = 060610
sidebar = 060610
player = 060610
card = 060610
shadow = 060610
main-secondary = 060610
button = 1F5B98
button-secondary = B2738C
button-active = 1F5B98
button-disabled    = 26233a
nav-active = 4F6DA3
play-button = 1F5B98
tab-active = 060610
notification = B2738C
notification-error = eb6f92
playback-bar = 1F5B98
misc = B2738C

[Eldritch]
; https://github.com/eldritch-theme/eldritch
text = B2738C
subtext = c0c0c3
nav-active-text = 060610
main = 060610
sidebar = 060610
player = 060610
card = 060610
shadow = 060610
main-secondary = 060610
button = 1F5B98
button-secondary = B2738C
button-active = 1F5B98
button-disabled    = 323449
nav-active = 4F6DA3
play-button = 1F5B98
tab-active = 060610
notification = B2738C
notification-error = 212337
playback-bar = 1F5B98
misc = B2738C

[Catppuccin]
; https://catppuccin.com/palette
text = B2738C
subtext = c0c0c3
nav-active-text = 060610
main = 060610
sidebar = 060610
player = 060610
card = 060610
shadow = 060610
main-secondary = 060610
button = 1F5B98
button-secondary = B2738C
button-active = 1F5B98
button-disabled    = 181825
nav-active = 4F6DA3
play-button = 1F5B98
tab-active = 060610
notification = B2738C
notification-error = 11111b
playback-bar = 1F5B98
misc = B2738C

[AyuDark]
; https://github.com/ayu-theme/ayu-colors
text = B2738C
subtext = c0c0c3
nav-active-text = 060610
main = 060610
sidebar = 060610
player = 060610
card = 060610
shadow = 060610
main-secondary = 060610
button = 1F5B98
button-secondary = B2738C
button-active = 1F5B98
button-disabled    = 181825
nav-active = 4F6DA3
play-button = 1F5B98
tab-active = 060610
notification = B2738C
notification-error = 0b0e14
playback-bar = 1F5B98
misc = B2738C


; Description

; text             = main text, playlist names in main field, name of playlist selected in sidebar, headings
; subtext          = text in main buttons in sidebar, playlist names in sidebar, artist names, and mini infos
; nav-active-text  = text in main buttons in sidebar when active
; main             = main bg
; main-secondary   = bg color of selected song rows, bg color of artist/track cards
; sidebar          = sidebar bg
; player           = player bg
; card             = popup-card bg
; shadow           = all shadows
; button           = playlist buttons bg in sidebar, drop-down menus, now playing song, like button
; button-secondary = download and options button
; button-active    = hover on song selected
; button-disabled  = seekbar bg, volume bar bg, scrollbar
; nav-active       = sidebar buttons bg
; play-button      = color of main play button in main field
; tab-active       = button bg in main field (playlists, podcasts, artists, albums)
; notification     = notification ('Added to liked songs' etc.)
; playback-bar     = seekbar fg, volume bar fg, main play/pause button
; misc             = miscellaneous

[pywal]
accent             = 0a0e19 
accent-active      = 98A3AA 
accent-inactive    = B2BBC3 
banner             = BBC4C8 
border-active      = c1c2c5 
border-inactive    = c1c2c5 
header             = c1c2c5 
highlight          = D5DCE1 
main = 060610
notification = B2738C
notification-error = 59606e 
subtext = c0c0c3
text = B2738C